name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy Gree Api Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependensies
        run: npm i

      - name: Build and Deploy to GitHub Pages
        run: npm run deploy
