name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy Gree Api Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Deploy React app to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
